# Generated by Django 5.2.8 on 2025-12-02 11:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutpage_body_alter_aboutpage_image_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='from_address',
            field=models.CharField(default='noreply@monsite.com', help_text='Adresse utilisée comme expéditeur des emails.', max_length=255, verbose_name='Adresse expéditeur'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(default='Nouveau message depuis votre site vitrine', max_length=255, verbose_name='Sujet de l’email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default='Merci ! Votre message a bien été envoyé.', verbose_name='Message de remerciement après envoi'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='to_address',
            field=models.CharField(default='contact@exemple.com', help_text='Les messages du formulaire seront envoyés à cette adresse.', max_length=255, verbose_name='Adresse email qui recevra les messages'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_preview',
            field=wagtail.fields.StreamField([('service', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du service', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le service (format horizontal de préférence).', 'label': 'Image du service', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, verbose_name='Services à afficher sur l’accueil (aperçu)'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services',
            field=wagtail.fields.StreamField([('service', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du service', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le service (format horizontal de préférence).', 'label': 'Image du service', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des services proposés.', verbose_name='Services'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
